[tool.poetry]
name = "cv_main"
version = "0.1.0"
description = ""
authors = ["Jeff Hykin <jeff.hykin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
opencv-contrib-python = "^4.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
cv_main = "source.main"